Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "xallro.net"
  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "gegrru"
    v.memory = 2048
    v.cpus = 1
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.synced_folder "../codi", "/var/www/html"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    # sudo apt-get upgrade -y
    sudo apt-get install -y aptitude net-tools apache2 apache2-doc libapache2-mod-php php7.4 mariadb-server mariadb-client php7.4-mysql
  SHELL

end
